include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Errors
    unrelated_type_equality_checks: error

    # warnings
    avoid_redundant_argument_values: warning
    deprecated_member_use: warning
    invalid_annotation_target: warning
    non_constant_identifier_names: warning
    use_super_parameters: warning
    no_literal_bool_comparisons: warning
    prefer_const_constructors: warning
    unnecessary_await_in_return: warning
    directives_ordering: warning
    prefer_final_fields: warning
    unnecessary_string_interpolations: warning
    unawaited_futures: warning

    #ignores
    use_build_context_synchronously: ignore
    constant_identifier_names: ignore
    avoid_void_async: ignore


linter:

  rules:
    - unrelated_type_equality_checks
    - avoid_redundant_argument_values
    - constant_identifier_names
    - non_constant_identifier_names
    - use_super_parameters
    - no_literal_bool_comparisons
    - use_build_context_synchronously
    - prefer_const_constructors
    - unnecessary_await_in_return
    - directives_ordering
    - prefer_final_fields
    - unnecessary_string_interpolations
    - unawaited_futures
    - avoid_void_async

