include: package:flutter_lints/flutter.yaml

linter:

  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Errors
    unrelated_type_equality_checks: error

    # ignores
    constant_identifier_names: warning
    deprecated_member_use: warning
    invalid_annotation_target: warning
    non_constant_identifier_names: warning
    use_super_parameters: warning
