include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Errors
    unrelated_type_equality_checks: error

    # warnings
    avoid_redundant_argument_values: warning
    constant_identifier_names: warning
    deprecated_member_use: warning
    invalid_annotation_target: warning
    non_constant_identifier_names: warning
    use_super_parameters: warning
    no_literal_bool_comparisons: warning

    #ignores
    use_build_context_synchronously: ignore


linter:

  rules:
    - unrelated_type_equality_checks
    - avoid_redundant_argument_values
    - constant_identifier_names
    - non_constant_identifier_names
    - use_super_parameters
    - no_literal_bool_comparisons
    - use_build_context_synchronously

