name: hoomo_pos
description: "A new Flutter project."
publish_to: 'none'

version: 1.5.2


environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1

  intl: ^0.19.0

  floating_dialog: ^1.1.1+1

  easy_localization: ^3.0.7+1

  provider: ^6.1.2

  auto_route: ^9.3.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0

  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  file_picker: ^10.2.0

  drift: ^2.24.0
  drift_flutter: ^0.2.4
  flutter_secure_storage: ^9.2.4
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3: ^2.7.4
  sqlite3_flutter_libs: ^0.5.0

  windows_notification: ^1.3.0

  freezed_annotation: ^2.4.4
  web_socket_channel: ^3.0.3
  json_annotation: ^4.9.0

  device_info_plus: ^11.3.0
  talker: ^4.6.11
  talker_dio_logger: ^4.6.11

  cached_network_image: ^3.4.1

  flutter_barcode_listener: ^0.1.4
  flutter_phoenix: ^1.1.1
  webview_windows: ^0.4.0
  logger: ^2.5.0
  updat: ^1.3.2
  package_info_plus: ^8.3.0
  flutter_svg: ^2.1.0
  rxdart: ^0.28.0
  datepicker_dropdown: ^0.1.7
  multi_dropdown: ^3.0.1
  uuid: ^4.5.1
  translit: ^2.0.2
  url_launcher: ^6.3.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  auto_route_generator: ^9.3.1
  drift_dev: ^2.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Semibold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
